In [2]:
import pandas as pd
import matplotlib.pyplot as plt

In [11]:
df=pd.read_csv("D:\\work\\data\\raw\\data.csv")
df.shape

(1512, 15)

In [12]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1512 entries, 0 to 1511
Data columns (total 15 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   Shipment_ID                         1512 non-null   str
 1   Dispatch_Date                       1512 non-null   str
 2   Product_Type                        1475 non-null   str
 3   Storage_Condition                   1475 non-null   str
 4   Initial_Shelf_Life_Hours            1475 non-null   float64
 5   Avg_Temperature_C                   1475 non-null   float64
 6   Min_Temperature_C                   1475 non-null   float64
 7   Max_Temperature_C                   1475 non-null   float64
 8   Temperature_Fluctuation_C           1475 non-null   float64
 9   Relative_Humidity_pct               1476 non-null   float64
 10  Transit_Elapsed_Hours               1475 non-null   float64
 11  Expected_Transit_Remaining_Hours    1475 non-null   float64
 12  Hours_Above_Product_Temp_Threshold  1475 non-null   float64
 13  Unplanned_Delay_Hours               1475 non-null   float64
 14  Remaining_Shelf_Life_Hours          1475 non-null   float64
dtypes: float64(11), str(4)
memory usage: 236.5 KB

In [13]:
df.isnull().sum()

Shipment_ID                            0
Dispatch_Date                          0
Product_Type                          37
Storage_Condition                     37
Initial_Shelf_Life_Hours              37
Avg_Temperature_C                     37
Min_Temperature_C                     37
Max_Temperature_C                     37
Temperature_Fluctuation_C             37
Relative_Humidity_pct                 36
Transit_Elapsed_Hours                 37
Expected_Transit_Remaining_Hours      37
Hours_Above_Product_Temp_Threshold    37
Unplanned_Delay_Hours                 37
Remaining_Shelf_Life_Hours            37
dtype: int64

In [18]:
print(df.duplicated().sum())

7

In [20]:
# Examine categorical values
print("Product types:")
print(df["Product_Type"].value_counts(dropna=False))

print("\nStorage conditions:")
print(df["Storage_Condition"].value_counts(dropna=False)) #added dropna=False so that it does not remove null values while considering the value counts

# Understand the target variable
print("\nRemaining shelf life information:")
print(df["Remaining_Shelf_Life_Hours"].describe())

# Check duplicate shipment IDs
print("\nDuplicate shipment IDs:", df["Shipment_ID"].duplicated().sum())

Product types:
Product_Type
Strawberries     277
Leafy Greens     260
Tomatoes         249
Bell Peppers     235
Blueberries      228
Bananas          222
NaN               37
Leafy Greens       3
Blueberries        1
Name: count, dtype: int64

Storage conditions:
Storage_Condition
Refrigerated    1026
Insulated        314
Ambient          131
NaN               37
refrigerated       4
Name: count, dtype: int64

Remaining shelf life information:
count    1475.000000
mean      115.894915
std        56.300753
min         0.000000
25%        74.100000
50%       109.100000
75%       156.900000
max       259.400000
Name: Remaining_Shelf_Life_Hours, dtype: float64

Duplicate shipment IDs: 12

In [27]:
# shipment IDs that occur more than once
duplicate_ids = df[df["Shipment_ID"].duplicated(keep=False)].sort_values("Shipment_ID")
display(duplicate_ids.head())
display(duplicate_ids)

,Shipment_ID,Dispatch_Date,Product_Type,Storage_Condition,Initial_Shelf_Life_Hours,Avg_Temperature_C,Min_Temperature_C,Max_Temperature_C,Temperature_Fluctuation_C,Relative_Humidity_pct,Transit_Elapsed_Hours,Expected_Transit_Remaining_Hours,Hours_Above_Product_Temp_Threshold,Unplanned_Delay_Hours,Remaining_Shelf_Life_Hours
226,SHP-00227,2025-04-23,Blueberries,Refrigerated,163.1,2.34,-0.60,5.17,5.78,96.6,22.1,30.4,2.3,4.5,136.7
1510,SHP-00227,2025-04-23,Blueberries,Refrigerated,163.1,2.34,-0.60,5.17,5.78,96.6,22.1,30.4,2.3,4.5,136.7
296,SHP-00297,2025-01-11,Blueberries,Refrigerated,126.7,5.62,4.79,7.40,2.61,91.2,15.7,23.4,15.2,1.0,105.6
1508,SHP-00297,2025-01-11,Blueberries,Refrigerated,126.7,5.62,4.79,7.40,2.61,91.2,15.7,23.4,15.2,1.0,105.6
324,SHP-00325,2025-08-27,Bananas,Refrigerated,217.5,17.01,15.36,18.51,NaN,83.5,41.7,6.8,27.6,6.4,168.1

,Shipment_ID,Dispatch_Date,Product_Type,Storage_Condition,Initial_Shelf_Life_Hours,Avg_Temperature_C,Min_Temperature_C,Max_Temperature_C,Temperature_Fluctuation_C,Relative_Humidity_pct,Transit_Elapsed_Hours,Expected_Transit_Remaining_Hours,Hours_Above_Product_Temp_Threshold,Unplanned_Delay_Hours,Remaining_Shelf_Life_Hours
226,SHP-00227,2025-04-23,Blueberries,Refrigerated,163.1,2.34,-0.60,5.17,5.78,96.6,22.1,30.4,2.3,4.5,136.7
1510,SHP-00227,2025-04-23,Blueberries,Refrigerated,163.1,2.34,-0.60,5.17,5.78,96.6,22.1,30.4,2.3,4.5,136.7
296,SHP-00297,2025-01-11,Blueberries,Refrigerated,126.7,5.62,4.79,7.40,2.61,91.2,15.7,23.4,15.2,1.0,105.6
1508,SHP-00297,2025-01-11,Blueberries,Refrigerated,126.7,5.62,4.79,7.40,2.61,91.2,15.7,23.4,15.2,1.0,105.6
324,SHP-00325,2025-08-27,Bananas,Refrigerated,217.5,17.01,15.36,18.51,NaN,83.5,41.7,6.8,27.6,6.4,168.1
1501,SHP-00325,2025-08-27,Bananas,Refrigerated,217.5,17.01,15.36,18.51,3.15,83.5,41.7,6.8,27.6,6.4,168.1
343,SHP-00344,2025-09-08,Strawberries,Insulated,100.0,6.92,4.20,9.69,5.49,93.4,27.2,31.4,26.5,1.8,48.6
1511,SHP-00344,2025-09-08,Strawberries,Insulated,100.0,6.92,4.20,9.69,5.49,93.4,27.2,31.4,26.5,1.8,48.6
506,SHP-00507,2025-01-09,Strawberries,Insulated,101.7,3.75,2.27,9.79,NaN,99.0,20.8,33.4,1.3,3.4,71.6
1503,SHP-00507,2025-01-09,Strawberries,Insulated,101.7,3.75,2.27,9.79,7.52,99.0,20.8,33.4,1.3,3.4,71.6
573,SHP-00574,2025-09-30,Leafy Greens,Refrigerated,123.6,5.26,2.85,12.19,9.34,92.5,48.4,24.1,5.1,6.3,66.9
1500,SHP-00574,2025-09-30,Leafy Greens,Refrigerated,123.6,5.26,2.85,12.19,9.34,92.5,48.4,24.1,5.1,6.3,66.9
582,SHP-00583,2025-02-01,Strawberries,Refrigerated,91.3,2.42,1.30,6.72,5.42,81.5,12.3,31.0,1.5,6.5,81.9
1507,SHP-00583,2025-02-01,Strawberries,NaN,91.3,2.42,1.30,6.72,5.42,81.5,12.3,31.0,1.5,6.5,81.9
1089,SHP-01090,2025-10-05,Bananas,Refrigerated,NaN,13.68,10.47,20.15,NaN,90.3,38.4,31.3,2.4,4.8,213.1
1502,SHP-01090,2025-10-05,Bananas,NaN,249.6,13.68,10.47,20.15,9.68,90.3,38.4,31.3,2.4,4.8,213.1
1107,SHP-01108,2025-03-23,Tomatoes,Ambient,150.9,26.73,NaN,30.58,6.93,85.5,55.7,24.3,46.3,3.3,57.6
1506,SHP-01108,2025-03-23,Tomatoes,Ambient,150.9,26.73,23.65,30.58,6.93,85.5,55.7,24.3,46.3,3.3,57.6
1196,SHP-01197,2025-08-03,Bell Peppers,Refrigerated,169.5,12.68,8.65,15.34,6.68,84.4,6.8,14.4,4.6,1.7,160.1
1504,SHP-01197,2025-08-03,Bell Peppers,Refrigerated,169.5,12.68,8.65,15.34,6.68,84.4,6.8,14.4,4.6,1.7,160.1
1386,SHP-01387,2025-07-22,Bell Peppers,Insulated,181.0,9.77,8.85,15.16,6.31,86.4,39.9,5.5,3.0,3.4,133.1
1509,SHP-01387,2025-07-22,Bell Peppers,Insulated,181.0,9.77,8.85,15.16,6.31,86.4,39.9,5.5,3.0,3.4,133.1
1441,SHP-01442,2025-08-13,Bananas,Refrigerated,257.0,10.65,8.90,17.64,8.74,93.3,11.1,11.6,0.8,1.8,240.2
1505,SHP-01442,2025-08-13,Bananas,Refrigerated,257.0,10.65,8.90,17.64,8.74,93.3,11.1,11.6,0.8,1.8,240.2

In [25]:
# read the category values,including hidden spaces that can't be seen
print("Product type representations:")
for value in df["Product_Type"].dropna().unique():
    print(repr(value))

Product type representations:
'Leafy Greens'
'Tomatoes'
'Strawberries'
'Blueberries'
'Bell Peppers'
'Bananas'
'Leafy Greens '
'Blueberries '

In [26]:
print("\nStorage condition representations:")
for value in df["Storage_Condition"].dropna().unique():
    print(repr(value))

Storage condition representations:
'Refrigerated'
'Insulated'
'Ambient'
'refrigerated'

In [28]:
# we are Standardising categorical text by removing spaces and capitalising the first letters
df["Product_Type"] = df["Product_Type"].str.strip()
df["Storage_Condition"] = (df["Storage_Condition"].str.strip().str.title())

In [32]:
print(df["Product_Type"].value_counts(dropna=False))
print(df["Storage_Condition"].value_counts(dropna=False))

Product_Type
Strawberries    277
Leafy Greens    263
Tomatoes        249
Bell Peppers    235
Blueberries     229
Bananas         222
NaN              37
Name: count, dtype: int64
Storage_Condition
Refrigerated    1030
Insulated        314
Ambient          131
NaN               37
Name: count, dtype: int64

In [36]:
df=df.drop_duplicates()
print("Rows after deleting the duplicates: ",len(df))
print("Remaining duplicate rows:", df.duplicated().sum())

Rows after deleting the duplicates:  1505
Remaining duplicate rows: 0